#!/bin/sh
CLASSPATH=src:test:data

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

java -Xmx1GB -cp $CLASSPATH jline.ConsoleRunner clojure.main -e "(use '[clojure.contrib.duck-streams :only (spit read-lines reader writer)] '[clojure.contrib def ns-utils pprint repl-utils shell-out]) (require '[clojure.contrib.str-utils2 :as s])(require 'labrepl) (labrepl/-main)$LABREPL_SWANK" -r