#!/bin/sh
CLASSPATH=src:test

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

java -cp $CLASSPATH jline.ConsoleRunner clojure.main -e "(use '[clojure.contrib def duck-streams ns-utils pprint repl-utils shell-out]) (require '[clojure.contrib.str-utils2 :as s])(require 'labrepl) (labrepl/-main)" -r