#!/bin/sh
CLASSPATH=$CLASSPATH:src:test:resources:data

# For lein 1
for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

# For lein 2
CLASSPATH=$CLASSPATH:`lein classpath`


java -Xmx1G -cp $CLASSPATH jline.ConsoleRunner clojure.main -i script/run.clj -r
